### ISSUE TITLE
🚏 Roadmap 

### ISSUE THREAD

**Issue by hanxiao** [jina-ai/docarray#131]
Before 1.0, all new features and breaking changes will only bump the minor version. That also means the list below will only mention those features/breaking changes that are necessary for that minor version. Patch release is triggered whenever a bug is fixed. Hence they are not tracked/planned here in advance. Bugs solved in patch release can be tracked in the [CHANGELOG](https://github.com/jina-ai/docarray/blob/main/CHANGELOG.md).

## `0.13`:
> on 20.04.2022

- [x] an example and documentation about using ES backend for traditional text search, e.g. works on `.text` and `.tags`
- [x] Benchmark 6 ops: C,R,U,D, find by NN, find by conditions on all backends we have. No CICD, no integration, just
  - [x]  a table of 6 rows and 6 columns in QPS, 
  - [x] details about the benchmark machine setup, CPU, core, Python version
  - [x] a reproducible script in the repo that can run as-is. 
  - [x] put the benchmark table in https://docarray.jina.ai/advanced/document-store/ and link to the script

## `0.12`
> on 07.04.2022
- [x] Documents the dataclass

## `0.11`
> on 01.04.2022
- [ ] ~~#143~~
- [x] https://github.com/jina-ai/docarray/issues/209 

## `0.10`
> on 28.03.2022
- [x] Dataclass to represent multimodal document with free schema. (@alaeddine-13  ) (#188 ) (intentionally undocumented!)
- [x] ES support (@davidbp @winstonww) (#207 )
- [x] Publish `.find` interface by documenting it: refactoring if needed and adding docs (@numb3r3 ) https://github.com/jina-ai/docarray/pull/197

## `0.9`:
> on 08.03.2022
- [x] Solve the poll-out column such as `embedding` and `vector` at DocumentArray level (#161 )
  - [x] Update all DocumentStore backend to the latest. P,Q,W,S (depends on the last one)
- [x] #156
- [x] ~~#157~~ (decided to drop this feature after discussion)
- [x] PQlite -> ANNLite renaming (#151  )
- [x] adding `lookuppy`-based QL to the `.find` interface (#150)

## `0.8`
> on 25.02.2022
- [x] `find`,`match` interface #93 
- [x] add & support serialization protocol via filename suffix #128 
- [x] Documentations for the above
